### ISSUE TITLE
are R13 and R4 swapped on board v1.0?

### ISSUE THREAD

**Issue by jrstrick** [skiselev/isa-opl2#1]
Hi. After building it many years ago but never being able to use it, I'm trying to bring my OPL2 board online. It works, but it's picking up a loud hum from the PS fan. Looking at the schematic, I find that my r1.0 board seems to have R13 and R4 swapped. This is consistent with your build photo. Which is correct?

**Comment by skiselev** [comment]
Hi,

I don't have PSU fan noise issue in my system.
The picture below shows 1.0. And it is one of my working v1.0 boards:

![ISA OPL2 Assembled Board](https://github.com/skiselev/isa-opl2/blob/main/images/ISA_OPL2-Complete_Board-800px.jpg)

It appears that R13 and R4 are indeed swapped on the silkscreen.
R4 should be 2.2k, and R13 should be 10k.

There was a slight change in the schematic between v1.0 and v1.1. v1.0 had a bug (a reverse engineering mistake) in the circuit, which I think is responsible for "soft" turn-on functionality - to avoid popping sounds when computer is turned on.
As a part of that change, I fixed the silkscreen too.

**Comment by jrstrick** [comment]
Okay. I switched the resistors and can confirm your results.

**Comment by jrstrick** [comment]
Went through the board carefully and found the problem. Of the 10k resistors r2-r=5, three of mine wound up with 1k resistors. Replaced the resistors and cleaned the flux off the board, and it works fine. Closing this issue.

**Comment by jrstrick** [comment]
Went through the board carefully and found the problem. Of the 10k resistors r2-r=5, three of mine wound up with 1k resistors. Replaced the resistors and cleaned the flux off the board, and it works fine. Closing this issue.
